### ISSUE TITLE
beta and se of GWAS summary statistics

### ISSUE THREAD

**Issue by WeiCSong** [pietznerm/crossplatform_mGWAS#1]
Hi,
  Thank you for the great resource on metabolite GWAS! I downloaded the summary statistics from GWAS catalogs, and found that they contained only p-value of each SNP. Is it possible to share the beta and se of each SNP? Or alternatively, is it possible to share the sample size and frequency of each SNP, which could be used to derive beta? Thank you very much for your help!

**Comment by pietznerm** [comment]
Hi Wei,

we are currently in the process making stats public and kindly ask for your patients.

Thanks,
Maik
